
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

// board flash
#define CGF_UF2_BOARD_FLASH_SECTORS 8
// #define CFG_UF2_FLASH_SIZE (1024 * 1024)

// bootloader
#define BOOTLOADER_SIZE 0x20000

#define BOARD_FLASH_BOOT_START 0x8000000UL
#define BOARD_FLASH_BOOTLOADER_END 0x8007FFFUL
#define BOARD_FLASH_BOOT_DESCRIPTOR 0x0801FF00UL

// backup?
#define BOARD_FLASH_BACKUP_BOOT_START 0x081E0000UL
#define BOARD_FLASH_BACKUP_BOOTLOADER_END 0x81FFF00UL
#define BOARD_FLASH_BACKUP_BOOT_DESCRIPTOR 0x081FFF00UL

#define BOOTLOADER_UF2_FAMILY_ID (((uint32_t)BOOT_FAMILY_ID))
#define BOARD_FLASH_BOOT_SIZE \
    ((uint32_t)(((BOARD_FLASH_BOOTLOADER_END - BOARD_FLASH_BOOT_START)))) // 0x30001

//firmware
#define BOARD_FLASH_APP_START 0x08020200 // 0x08020000 + 0x0200 (512) vect table offset
#define BOARD_FLASH_APP_DESCRIPTOR 0x8020000
#define BOARD_FLASH_APP_END 0x807FFFF
#define BOARD_FLASH_APP_DESCRIPTOR 0x8020000 // 0x0805FF00UL
#define FIRMWARE_UF2_FAMILY_ID (((uint32_t)APP_FAMILY_ID))
#define BOARD_FLASH_APP_SIZE ((uint32_t)(((BOARD_FLASH_APP_END - BOARD_FLASH_APP_START))))


// rtc backup register signatures
#define BOOT_UPGRADE_INTERRUPTED_SIGNATURE BOOTLOADER_UF2_FAMILY_ID // same as bootloader fw family id
#define FW_UPGRADE_INTERRUPTED_SIGNATURE FIRMWARE_UF2_FAMILY_ID // same as bootloader fw family id

// common
#define UF2_PRODUCT_NAME PROJECT_NAME
#define UF2_BOARD_ID PROJECT_MODULE_ID
#define UF2_FLAG_FAMILYID 0x00002000

// common
#define BOARD_FLASH_END 0x081FFFFF

#ifdef __cplusplus
}
#endif